//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS_batch_backend.LilosoftMain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.lilosoft/", ConfigurationName="LilosoftMain.CardServiceDelegate")]
    public interface CardServiceDelegate {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        KMS_batch_backend.LilosoftMain.CheckCellphoneResponse CheckCellphone(KMS_batch_backend.LilosoftMain.CheckCellphoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckCellphoneResponse> CheckCellphoneAsync(KMS_batch_backend.LilosoftMain.CheckCellphoneRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        KMS_batch_backend.LilosoftMain.CheckBankcardResponse CheckBankcard(KMS_batch_backend.LilosoftMain.CheckBankcardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBankcardResponse> CheckBankcardAsync(KMS_batch_backend.LilosoftMain.CheckBankcardRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        KMS_batch_backend.LilosoftMain.CheckIdcardResponse CheckIdcard(KMS_batch_backend.LilosoftMain.CheckIdcardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckIdcardResponse> CheckIdcardAsync(KMS_batch_backend.LilosoftMain.CheckIdcardRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        KMS_batch_backend.LilosoftMain.CheckBadRecordResponse CheckBadRecord(KMS_batch_backend.LilosoftMain.CheckBadRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadRecordResponse> CheckBadRecordAsync(KMS_batch_backend.LilosoftMain.CheckBadRecordRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        KMS_batch_backend.LilosoftMain.CheckBadInfosResponse CheckBadInfos(KMS_batch_backend.LilosoftMain.CheckBadInfosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadInfosResponse> CheckBadInfosAsync(KMS_batch_backend.LilosoftMain.CheckBadInfosRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        KMS_batch_backend.LilosoftMain.CheckBadDetailResponse CheckBadDetail(KMS_batch_backend.LilosoftMain.CheckBadDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadDetailResponse> CheckBadDetailAsync(KMS_batch_backend.LilosoftMain.CheckBadDetailRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        KMS_batch_backend.LilosoftMain.QueryBalanceResponse QueryBalance(KMS_batch_backend.LilosoftMain.QueryBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.QueryBalanceResponse> QueryBalanceAsync(KMS_batch_backend.LilosoftMain.QueryBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckCellphoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckCellphone", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckCellphoneRequestBody Body;
        
        public CheckCellphoneRequest() {
        }
        
        public CheckCellphoneRequest(KMS_batch_backend.LilosoftMain.CheckCellphoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckCellphoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public CheckCellphoneRequestBody() {
        }
        
        public CheckCellphoneRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckCellphoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckCellphoneResponse", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckCellphoneResponseBody Body;
        
        public CheckCellphoneResponse() {
        }
        
        public CheckCellphoneResponse(KMS_batch_backend.LilosoftMain.CheckCellphoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckCellphoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CheckCellphoneResponseBody() {
        }
        
        public CheckCellphoneResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBankcardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBankcard", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckBankcardRequestBody Body;
        
        public CheckBankcardRequest() {
        }
        
        public CheckBankcardRequest(KMS_batch_backend.LilosoftMain.CheckBankcardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBankcardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public CheckBankcardRequestBody() {
        }
        
        public CheckBankcardRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBankcardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBankcardResponse", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckBankcardResponseBody Body;
        
        public CheckBankcardResponse() {
        }
        
        public CheckBankcardResponse(KMS_batch_backend.LilosoftMain.CheckBankcardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBankcardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CheckBankcardResponseBody() {
        }
        
        public CheckBankcardResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckIdcardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckIdcard", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckIdcardRequestBody Body;
        
        public CheckIdcardRequest() {
        }
        
        public CheckIdcardRequest(KMS_batch_backend.LilosoftMain.CheckIdcardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckIdcardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public CheckIdcardRequestBody() {
        }
        
        public CheckIdcardRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckIdcardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckIdcardResponse", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckIdcardResponseBody Body;
        
        public CheckIdcardResponse() {
        }
        
        public CheckIdcardResponse(KMS_batch_backend.LilosoftMain.CheckIdcardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckIdcardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CheckIdcardResponseBody() {
        }
        
        public CheckIdcardResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBadRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBadRecord", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckBadRecordRequestBody Body;
        
        public CheckBadRecordRequest() {
        }
        
        public CheckBadRecordRequest(KMS_batch_backend.LilosoftMain.CheckBadRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBadRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public CheckBadRecordRequestBody() {
        }
        
        public CheckBadRecordRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBadRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBadRecordResponse", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckBadRecordResponseBody Body;
        
        public CheckBadRecordResponse() {
        }
        
        public CheckBadRecordResponse(KMS_batch_backend.LilosoftMain.CheckBadRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBadRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CheckBadRecordResponseBody() {
        }
        
        public CheckBadRecordResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBadInfosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBadInfos", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckBadInfosRequestBody Body;
        
        public CheckBadInfosRequest() {
        }
        
        public CheckBadInfosRequest(KMS_batch_backend.LilosoftMain.CheckBadInfosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBadInfosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public CheckBadInfosRequestBody() {
        }
        
        public CheckBadInfosRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBadInfosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBadInfosResponse", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckBadInfosResponseBody Body;
        
        public CheckBadInfosResponse() {
        }
        
        public CheckBadInfosResponse(KMS_batch_backend.LilosoftMain.CheckBadInfosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBadInfosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CheckBadInfosResponseBody() {
        }
        
        public CheckBadInfosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBadDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBadDetail", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckBadDetailRequestBody Body;
        
        public CheckBadDetailRequest() {
        }
        
        public CheckBadDetailRequest(KMS_batch_backend.LilosoftMain.CheckBadDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBadDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public CheckBadDetailRequestBody() {
        }
        
        public CheckBadDetailRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBadDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBadDetailResponse", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.CheckBadDetailResponseBody Body;
        
        public CheckBadDetailResponse() {
        }
        
        public CheckBadDetailResponse(KMS_batch_backend.LilosoftMain.CheckBadDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBadDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CheckBadDetailResponseBody() {
        }
        
        public CheckBadDetailResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryBalance", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.QueryBalanceRequestBody Body;
        
        public QueryBalanceRequest() {
        }
        
        public QueryBalanceRequest(KMS_batch_backend.LilosoftMain.QueryBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public QueryBalanceRequestBody() {
        }
        
        public QueryBalanceRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryBalanceResponse", Namespace="http://service.lilosoft/", Order=0)]
        public KMS_batch_backend.LilosoftMain.QueryBalanceResponseBody Body;
        
        public QueryBalanceResponse() {
        }
        
        public QueryBalanceResponse(KMS_batch_backend.LilosoftMain.QueryBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryBalanceResponseBody() {
        }
        
        public QueryBalanceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CardServiceDelegateChannel : KMS_batch_backend.LilosoftMain.CardServiceDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardServiceDelegateClient : System.ServiceModel.ClientBase<KMS_batch_backend.LilosoftMain.CardServiceDelegate>, KMS_batch_backend.LilosoftMain.CardServiceDelegate {
        
        public CardServiceDelegateClient() {
        }
        
        public CardServiceDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardServiceDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardServiceDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardServiceDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMS_batch_backend.LilosoftMain.CheckCellphoneResponse KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckCellphone(KMS_batch_backend.LilosoftMain.CheckCellphoneRequest request) {
            return base.Channel.CheckCellphone(request);
        }
        
        public string CheckCellphone(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckCellphoneRequest inValue = new KMS_batch_backend.LilosoftMain.CheckCellphoneRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckCellphoneRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            KMS_batch_backend.LilosoftMain.CheckCellphoneResponse retVal = ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckCellphone(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckCellphoneResponse> KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckCellphoneAsync(KMS_batch_backend.LilosoftMain.CheckCellphoneRequest request) {
            return base.Channel.CheckCellphoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckCellphoneResponse> CheckCellphoneAsync(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckCellphoneRequest inValue = new KMS_batch_backend.LilosoftMain.CheckCellphoneRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckCellphoneRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckCellphoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMS_batch_backend.LilosoftMain.CheckBankcardResponse KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckBankcard(KMS_batch_backend.LilosoftMain.CheckBankcardRequest request) {
            return base.Channel.CheckBankcard(request);
        }
        
        public string CheckBankcard(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckBankcardRequest inValue = new KMS_batch_backend.LilosoftMain.CheckBankcardRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckBankcardRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            KMS_batch_backend.LilosoftMain.CheckBankcardResponse retVal = ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckBankcard(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBankcardResponse> KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckBankcardAsync(KMS_batch_backend.LilosoftMain.CheckBankcardRequest request) {
            return base.Channel.CheckBankcardAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBankcardResponse> CheckBankcardAsync(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckBankcardRequest inValue = new KMS_batch_backend.LilosoftMain.CheckBankcardRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckBankcardRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckBankcardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMS_batch_backend.LilosoftMain.CheckIdcardResponse KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckIdcard(KMS_batch_backend.LilosoftMain.CheckIdcardRequest request) {
            return base.Channel.CheckIdcard(request);
        }
        
        public string CheckIdcard(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckIdcardRequest inValue = new KMS_batch_backend.LilosoftMain.CheckIdcardRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckIdcardRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            KMS_batch_backend.LilosoftMain.CheckIdcardResponse retVal = ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckIdcard(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckIdcardResponse> KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckIdcardAsync(KMS_batch_backend.LilosoftMain.CheckIdcardRequest request) {
            return base.Channel.CheckIdcardAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckIdcardResponse> CheckIdcardAsync(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckIdcardRequest inValue = new KMS_batch_backend.LilosoftMain.CheckIdcardRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckIdcardRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckIdcardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMS_batch_backend.LilosoftMain.CheckBadRecordResponse KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckBadRecord(KMS_batch_backend.LilosoftMain.CheckBadRecordRequest request) {
            return base.Channel.CheckBadRecord(request);
        }
        
        public string CheckBadRecord(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckBadRecordRequest inValue = new KMS_batch_backend.LilosoftMain.CheckBadRecordRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckBadRecordRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            KMS_batch_backend.LilosoftMain.CheckBadRecordResponse retVal = ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckBadRecord(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadRecordResponse> KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckBadRecordAsync(KMS_batch_backend.LilosoftMain.CheckBadRecordRequest request) {
            return base.Channel.CheckBadRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadRecordResponse> CheckBadRecordAsync(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckBadRecordRequest inValue = new KMS_batch_backend.LilosoftMain.CheckBadRecordRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckBadRecordRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckBadRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMS_batch_backend.LilosoftMain.CheckBadInfosResponse KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckBadInfos(KMS_batch_backend.LilosoftMain.CheckBadInfosRequest request) {
            return base.Channel.CheckBadInfos(request);
        }
        
        public string CheckBadInfos(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckBadInfosRequest inValue = new KMS_batch_backend.LilosoftMain.CheckBadInfosRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckBadInfosRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            KMS_batch_backend.LilosoftMain.CheckBadInfosResponse retVal = ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckBadInfos(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadInfosResponse> KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckBadInfosAsync(KMS_batch_backend.LilosoftMain.CheckBadInfosRequest request) {
            return base.Channel.CheckBadInfosAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadInfosResponse> CheckBadInfosAsync(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckBadInfosRequest inValue = new KMS_batch_backend.LilosoftMain.CheckBadInfosRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckBadInfosRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckBadInfosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMS_batch_backend.LilosoftMain.CheckBadDetailResponse KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckBadDetail(KMS_batch_backend.LilosoftMain.CheckBadDetailRequest request) {
            return base.Channel.CheckBadDetail(request);
        }
        
        public string CheckBadDetail(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckBadDetailRequest inValue = new KMS_batch_backend.LilosoftMain.CheckBadDetailRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckBadDetailRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            KMS_batch_backend.LilosoftMain.CheckBadDetailResponse retVal = ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckBadDetail(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadDetailResponse> KMS_batch_backend.LilosoftMain.CardServiceDelegate.CheckBadDetailAsync(KMS_batch_backend.LilosoftMain.CheckBadDetailRequest request) {
            return base.Channel.CheckBadDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.CheckBadDetailResponse> CheckBadDetailAsync(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.CheckBadDetailRequest inValue = new KMS_batch_backend.LilosoftMain.CheckBadDetailRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.CheckBadDetailRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).CheckBadDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMS_batch_backend.LilosoftMain.QueryBalanceResponse KMS_batch_backend.LilosoftMain.CardServiceDelegate.QueryBalance(KMS_batch_backend.LilosoftMain.QueryBalanceRequest request) {
            return base.Channel.QueryBalance(request);
        }
        
        public string QueryBalance(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.QueryBalanceRequest inValue = new KMS_batch_backend.LilosoftMain.QueryBalanceRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.QueryBalanceRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            KMS_batch_backend.LilosoftMain.QueryBalanceResponse retVal = ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).QueryBalance(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.QueryBalanceResponse> KMS_batch_backend.LilosoftMain.CardServiceDelegate.QueryBalanceAsync(KMS_batch_backend.LilosoftMain.QueryBalanceRequest request) {
            return base.Channel.QueryBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMS_batch_backend.LilosoftMain.QueryBalanceResponse> QueryBalanceAsync(string arg0, string arg1) {
            KMS_batch_backend.LilosoftMain.QueryBalanceRequest inValue = new KMS_batch_backend.LilosoftMain.QueryBalanceRequest();
            inValue.Body = new KMS_batch_backend.LilosoftMain.QueryBalanceRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((KMS_batch_backend.LilosoftMain.CardServiceDelegate)(this)).QueryBalanceAsync(inValue);
        }
    }
}
